version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: interview_db
    restart: always
    environment:
      MYSQL_DATABASE: interview_prep
      MYSQL_USER: interview_user
      MYSQL_PASSWORD: Shiva@9876#Data
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      # Forward host port 3307 to container port 3306 to avoid conflicts with host's local MySQL
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build: .
    container_name: interview_web
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      # Bind mount the local codebase for hot-reloading in development
      - .:/app
    ports:
      - "9999:8000"
    environment:
      - DB_NAME=interview_prep
      - DB_USER=interview_user
      - DB_PASSWORD=Shiva@9876#Data
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: interview_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9091:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:10.0.0
    container_name: interview_grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: interview_node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "9101:9100"

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.14.0
    container_name: interview_mysqld_exporter
    restart: always
    environment:
      - "DATA_SOURCE_NAME=interview_user:Shiva@9876#Data@(db:3306)/interview_prep"
    ports:
      - "9105:9104"
    depends_on:
      db:
        condition: service_healthy
  # nvidia-gpu-exporter:
  #   image: utkuozdemir/nvidia_gpu_exporter:v1.2.0
  #   container_name: interview_nvidia_gpu_exporter
  #   restart: always
  #   ports:
  #     - "9835:9835"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]


volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
